### ISSUE TITLE
Qml.Net.Internal.Interop failing to find runtime even with RuntimeManager.DiscoverOrDownloadSuitableQtRuntime() called in the first line of main

### ISSUE THREAD

**Issue by besmith43** [pauldotknopf/net-core-qml#217]
I apologize if this is a duplicate and/or I'm making a simple mistake, however I'm running to an issue where the Qml.Net.Internal.Interop is failing to find a runtime even with the RuntimeManager.DiscoverOrDownloadSuitableQtRuntime() called in the first line of main.  I have tested this behavior across 3 environments (my personal windows 10 dev laptop, Windows Sandbox, and a fresh install of Windows 10 on a desktop) and attempted to run with .Net Framework 4.8, and .Net Core 3.1.6.  On my personal dev machine, everything is fine.  On the "deployment" machines (aka the sandbox and desktop) it fails with the error described.  I've created a repo of a "hello world" project and included a number of the debugging questions that you've asked of others with similar problems such as the environment variables and a picture of the complete error given before failure.  Additionally I have a powershell script with the commands that I used to publish each of the 3 project variants tested.  If there is any additional information that would be beneficial in addressing this, please let me know and thanks in advance for looking at it.

[repo](https://github.com/besmith43/qml.net-issue)

**Comment by pauldotknopf** [comment]
Your repo worked for me under Linux.

![image](https://user-images.githubusercontent.com/523150/90867739-db602480-e363-11ea-8a03-2c5e82d34261.png)

If you could, could you take a look at the runtime that was downloaded (check your env vars for the actual path), and verify that the Qt libraries has all it's dependencies installed? VC++, etc.

**Comment by besmith43** [comment]
That perfectly explains it.  The Windows Sandbox doesn't install the VC++ runtime and the blank Windows 10 system that I had didn't have any additional software installed.  However once I installed the VC++ runtime, both worked beautifully.
Sorry to have wasted your time, but thank you for looking at it

**Comment by vadi2** [comment]
Is this a common scenario users might have?

**Comment by pauldotknopf** [comment]
@vadi2, I think so. I definitely think some checks for the VC runtime should be added in QmlNet sooner rather than later.
