### ISSUE TITLE
How to pass a list to C#?

### ISSUE THREAD

**Issue by vadi2** [pauldotknopf/net-core-qml#218]
I need to pass a list of `url`s from QML to a C# method.

So far I've tried `List<string>` as the parameter signature on the C# side and converted all of the `url`s to `string`s in QML, which does seem to create a parameter on the C#, but that list is empty as far as it's concerned.

```js
                    FileDialog {
                        id: resourcePicker
                        onAccepted: {console.log(convertUriToString(resourcePicker.files)); appmodel.loadResourceFile(convertUriToString(resourcePicker.files))}
                        fileMode: FileDialog.OpenFiles

                        function convertUriToString(files) {
                            var stringFiles = [];
                            for (var i  = 0; i < files.length; i++) {
                                stringFiles.push(files[i].toString());
                            }

                            return stringFiles;
                        }
                    }
```

```csharp
public bool LoadResourceFile (List<string> files) {
```

**Comment by pauldotknopf** [comment]
Pass the array to C# as a ```INetJsValue```, then use ```AsList<T>()``` to convert that javascript value to a list.

There is plans to eventually make this more seamless.

https://github.com/qmlnet/qmlnet/blob/845913eb3b14887879888cec0e7d0c914c21a30c/src/net/Qml.Net/Extensions/INetJsValueExtensions.cs#L9
