### ISSUE TITLE
signal link progressbar 

### ISSUE THREAD

**Issue by lilongueti** [pauldotknopf/net-core-qml#220]
trying to do a NotifySignal from a float to ProgressBar.value but it doesn't seem to work, placing the event somewhere else does assign de value properly but just setting ProgressBar.value=model.Percentage does nothing

**Comment by devmil** [comment]
Hi,
did you get a QML error that Percentage is no property?
QML.Net converts the property names to camelCase because this is the QML standard.
So maybe just using `model.percentage` solves your problem?

**Comment by lilongueti** [comment]
i'm not 100% sure what was it, i did use proper casing, however it is working now, thanks
