### ISSUE TITLE
Getting C# reference to RegisterSingletonType instance 

### ISSUE THREAD

**Issue by YTN0** [pauldotknopf/net-core-qml#235]
I am new to qt / qml and have started experimenting with using qml.net. So far it's been working really well. I have not been able to figure out how to get the reference to a singleton instance in my c# code. I have used the RegisterSingletonType method which works fine, and I can use the singleton instance in the qml code without issues.

However, I need to reference the same singleton instance from c# to update some data. Can someone please clarify how this can be done?

Thanks.

**Comment by pauldotknopf** [comment]
I'm not sure there is a way.

I guess you can update the ```ctor``` of your .NET type, to put ```this``` into a static variable that can be accessed elsewhere?

**Comment by YTN0** [comment]
Thanks for the response. I managed to find a solution for this.
