### ISSUE TITLE
libQmlNet.so: undefined symbol on newer Linux

### ISSUE THREAD

**Issue by hengestone** [pauldotknopf/net-core-qml#241]
Trying to run an example on Ubuntu 21.04 I get:
```
$> dotnet run

Unhandled exception. System.TypeInitializationException: 
The type initializer for 'Qml.Net.Internal.Interop' threw an exception.
 ---> System.Exception: Library could not be loaded: 
***/qt/qmldotnet/bin/Debug/net5.0/runtimes/linux-x64/native/libQmlNet.so: undefined symbol:
_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version Qt_5
```
The symbol is defined in `libstdc++.so.6.0.29` as expected. And `libdl.so.2` is available and loaded when the above is run (from strace output).

My suspicion is that `Qml.Net.LinuxBinaries` needs to be rebuilt, but I'm not sure.

Any ideas?
Thanks!

**Comment by pauldotknopf** [comment]
Ya, it needs to be rebuilt. I'm guessing gcc is different/newer on Ubuntu 21.04.

**Comment by hengestone** [comment]
What is the best way to handle that? Build a custom version on MyGet and reference it in the project file? Or is there a way to rebuild the dependency locally? (I tried to find the answer in the dot net docs :-/ )

**Comment by pauldotknopf** [comment]
The best bet is to avoid installing any of the ```*.Native*``` nuget packages, and build ```libQmlnet.so``` locally and put it in ```/usr/local/lib``` (or wherever it needs to be).

**Comment by hengestone** [comment]
Thanks :)
