### ISSUE TITLE
Missing header file?

### ISSUE THREAD

**Issue by khionu** [pauldotknopf/net-core-qml#67]
I'm trying to find the behavior of `QQmlApplicationEngine.LoadData(string)`, and I reached a dead end in the C++ code. I'm not exactly well versed in C++, but I noticed this header import that doesn't exist in the repository? I was hoping you could explain this.

https://github.com/pauldotknopf/Qml.Net/blob/develop/src/native/QmlNet/QmlNet/qml/QQmlApplicationEngine.cpp#L6

Additionally, if you have a better venue for discussion, I would appreciate a link, and would suggest putting it in your README.

**Comment by pauldotknopf** [comment]
This is the C++ you are looking for: https://github.com/pauldotknopf/Qml.Net/blob/93d97ecc94602cd8fd43b4337cb66d7f8b2ac05a/src/native/QmlNet/QmlNet/qml/QQmlApplicationEngine.cpp#L35

You can chat here: https://qmlnet.slack.com/

**Comment by khionu** [comment]
Slack is an invite-only platform. If you don't mind inviting me, you can use the email I use in my commits `dev@khionu.net`, otherwise we would have to use another platform.

**Comment by pauldotknopf** [comment]
I added the new chat link to the README. Here it is: https://gitter.im/godarch/Lobby

Did you find everything you were looking for?

**Comment by khionu** [comment]
I'm afraid not. The header I linked is not anywhere I can find. I did figure out the behavior from experimenting, but that doesn't solve the mystery I opened this for.
